META_DATA <- "metaData"
IS_AVAILABLE <- "isAvailable"
REVISION_HISTORY <- "revisionHistory"
FIELDS_BY_SERVICE <- "fieldsByService"
ISSUES <- "issues"

LIST <- "list"
STATES <- "states"
COUNTIES_BY_STATE <- "countiesByState"
SITES_BY_COUNTY <- "sitesByCounty"
CBSAS <- "cbsas"
PARAMETER_CLASSES <- "classes"
PARAMETERS_WITHIN_CLASS <- "parametersByClass"
PQAOS <- "pqaos"
MAS <- "mas"